bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'abouts/show'
  root 'homes#index'
  devise_for :users
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

bookers2/app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
end

bookers2/app/helpers/abouts_helper.rb
module AboutsHelper
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/user_helper.rb
module UserHelper
end

bookers2/app/views/abouts/show.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
  <div class="container">  
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">      
        <li>
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home">
            Home
          </span>
        <% end %>
        </li>
        <li>
          <%= link_to abouts_show_path do %>
            <span class="glyphicon glyphicon-link">
            About
            </span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-edit">
              sign up
            </span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in">
              login
            </span>
        <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>
          Welcome to
          <span class="glyphicon glyphicon-book"><strong>Bookers!</strong></span>
        </h1>
      </div>
    </div>
  </div>
</div>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

bookers2/app/views/homes/index.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
  <div class="container">  
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">      
        <li>
        <%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-home">
            Home
          </span>
        <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-link">
            About
            </span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-edit">
              sign up
            </span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in">
              login
            </span>
        <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>
<div class="body">
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>
          welcome to
          <span class="glyphicon glyphicon-book"><strong>Bookers</strong> !!</span>
        </h1>
        <p>
          In
          <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,
        </p>
        <p>
          you can share and exchange your opinions , inpressions , and emotions
        </p>
        <p>
          about varioius books!
        </p>
        <div class="btn-wrapper">
          <div class="row">
            <p>
              <%= link_to 'Log in',new_user_session_path,class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
            </p>
          </div>
          <div class="row">
            <p>
              <%= link_to 'Sign Up',new_user_session_path,class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>